### ISSUE TITLE
arduino_keyboard: "Hello World" is typed as "Helo World"

### ISSUE THREAD

**Issue by agausmann** [agausmann/atmega-usbd#5]
The reports for the two "L" keypresses are identical, which supposedly makes the host PC think that the "L" key has been held down.

Possible solutions:
- Send an empty report in between identical characters
- (Possibly simpler) Send an empty report between all characters

**Comment by kanashimia** [comment]
I fixed this myself by adding a case for `b'\0'` that sends empty report, and the modified the string to contain it between L's.
There is even a simpler solution by replacing `Hello world` with something that doesn't contain double characters, but than users won't understand why some different string wont work.

**Comment by stappersg** [comment]
In another attempt to add value, a.k.a. _noise warning_: 


Arent' there _"key pressed"_ **and** "key released"  key codes?

https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html says so ...

**Comment by agausmann** [comment]
> Arent' there "key pressed" and "key released" key codes?

"Scan codes" are not the same as the keycodes defined in the [HID Usage Tables](https://www.usb.org/document-library/hid-usage-tables-13) (usage page 0x07 is the one for keyboard keys)

There is no concept of press and release events in HID (at least not in the standard keyboard report), just the state of whether the key is currently pressed or not.

**Comment by agausmann** [comment]
Should be fixed by a9b148808886b8b7baf4802c1375cb9fec594711
